const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=$('#toast'),API='/api';let token=localStorage.getItem('expomind-token')||'',authMode='login',currentUser=null,contacts=[],conversations=[],selectedContact=null,editingContactId=null,stream=null,recognition=null,tracking=false,lastAnalysis=null;
function notify(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1900)}
async function request(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(`${API}${path}`,{...options,headers});const data=await response.json().catch(()=>({}));if(response.status===401&&path!=='/auth/login'){logout(false)}if(!response.ok)throw new Error(data.detail||'Request failed');return data}
async function upload(path,form){const response=await fetch(`${API}${path}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||'Upload failed');return data}

function setAuthMode(mode){authMode=mode;const register=mode==='register';$('#authForm').classList.toggle('registering',register);$('#authEyebrow').textContent=register?'GET STARTED':'WELCOME BACK';$('#authTitle').textContent=register?'Create your ExpoMind account':'Sign in to your workspace';$('#authSubtitle').textContent=register?'Start with an empty, private workspace.':'Continue your exhibition intelligence workflow.';$('#authSubmit').textContent=register?'Create account':'Sign in';$('#authQuestion').textContent=register?'Already have an account?':'New to ExpoMind?';$('#authSwitch').textContent=register?'Sign in':'Create account';$('#authError').textContent=''}
function logout(message=true){token='';currentUser=null;localStorage.removeItem('expomind-token');$('#authScreen').classList.remove('hidden');if(message)notify('Signed out safely')}
async function showWorkspace(user){currentUser=user;$('#authScreen').classList.add('hidden');$('#accountBtn').textContent=user.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();$('.admin-only').classList.toggle('visible',user.role==='admin');await refreshData();if(user.role==='admin')loadUsers()}
$('#authSwitch').onclick=()=>setAuthMode(authMode==='login'?'register':'login');
$('#authForm').onsubmit=async e=>{e.preventDefault();const b=$('#authSubmit');b.disabled=true;$('#authError').textContent='';try{const body={email:$('#authEmail').value.trim(),password:$('#authPassword').value};if(authMode==='register')body.name=$('#authName').value.trim();const data=await request(`/auth/${authMode}`,{method:'POST',body:JSON.stringify(body)});token=data.access_token;localStorage.setItem('expomind-token',token);await showWorkspace(data.user);notify(authMode==='register'?'Account created with an empty workspace':'Welcome back')}catch(error){$('#authError').textContent=error.message}finally{b.disabled=false;b.textContent=authMode==='login'?'Sign in':'Create account'}};
$('#accountBtn').onclick=()=>{if(confirm('Sign out of ExpoMind?'))logout()};

function switchView(view){$$('.view').forEach(x=>x.classList.remove('active-view'));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$(`#view-${view}`).classList.add('active-view');if(view==='graph')renderGraph();if(view==='admin')loadUsers()}
$$('.nav-item').forEach(x=>x.onclick=()=>switchView(x.dataset.view));
async function refreshData(){const [contactRows,conversationRows,dashboard]=await Promise.all([request('/contacts'),request('/conversations'),request('/dashboard')]);contacts=contactRows;conversations=conversationRows;renderContacts();renderTasks();updateMetrics(dashboard)}
function updateMetrics(data){$('#contactCount').textContent=data.contacts;$('#metricContacts').textContent=data.contacts;$('#metricHigh').textContent=data.high_intent;$('#metricConversations').textContent=data.conversations;const actions=conversations.filter(x=>x.next_action?.trim()).length;$('#metricTasks').textContent=actions;$('#taskCount').textContent=actions;$('.today-card strong').textContent=data.contacts;$('.today-card span').textContent='stored contacts';$('.today-card small').textContent=`${data.high_intent} qualified leads`}

function initials(name){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function renderContacts(q=''){const found=contacts.filter(x=>`${x.name} ${x.company} ${x.role} ${x.interests}`.toLowerCase().includes(q.toLowerCase()));$('#contactList').innerHTML=found.length?found.map(x=>`<div class="contact-row"><div class="contact-person"><div class="contact-avatar">${initials(x.name)}</div><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.role||'Role not recorded')}</small></div></div><div><b>${escapeHtml(x.company)}</b><small>${new Date(x.created_at).toLocaleDateString()}</small></div><div class="contact-topics">${x.interests.split(',').filter(Boolean).map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><div class="probability">${x.score}%</div><div class="row-actions"><button data-select="${x.id}">Select</button><button data-edit="${x.id}">Edit</button><button class="danger" data-delete="${x.id}">Delete</button></div></div>`).join(''):'<div class="list-empty">No contacts yet. Create the first verified contact.</div>';$$('[data-select]').forEach(b=>b.onclick=()=>selectContact(Number(b.dataset.select)));$$('[data-edit]').forEach(b=>b.onclick=()=>editContact(Number(b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteContact(Number(b.dataset.delete)))}
function escapeHtml(value=''){const d=document.createElement('div');d.textContent=value;return d.innerHTML}
$('#contactSearch').oninput=e=>renderContacts(e.target.value);
function selectContact(id){selectedContact=contacts.find(x=>x.id===id);if(!selectedContact)return;$('#contactEmpty').hidden=true;$('#contactInsight').hidden=false;$('#selectedInitials').childNodes[0].textContent=initials(selectedContact.name);$('#selectedName').textContent=selectedContact.name;$('#selectedCompany').textContent=`${selectedContact.company}${selectedContact.role?' · '+selectedContact.role:''}`;$('#selectedTags').innerHTML=`<span>${selectedContact.score>=75?'High intent':'Qualified contact'}</span>`;$('#score').textContent=`${selectedContact.score}%`;$('#scoreBar').style.width=`${selectedContact.score}%`;$('#selectedInterests').innerHTML=selectedContact.interests.split(',').filter(Boolean).map(x=>`<span>${escapeHtml(x)}</span>`).join('')||'<span>Not recorded</span>';$('#liveTranscriptCopy').textContent=$('#transcript').textContent;switchView('live');notify(`${selectedContact.name} selected from PostgreSQL`)}

const contactModal=$('#contactModal');function openContactModal(){editingContactId=null;$('#contactForm').reset();$('#contactScore').value=50;contactModal.classList.add('open')}function editContact(id){const x=contacts.find(c=>c.id===id);if(!x)return;editingContactId=id;$('#contactName').value=x.name;$('#contactCompany').value=x.company;$('#contactRole').value=x.role;$('#contactInterests').value=x.interests;$('#contactScore').value=x.score;contactModal.classList.add('open')}async function deleteContact(id){const x=contacts.find(c=>c.id===id);if(!x||!confirm(`Delete ${x.name} and all related conversations? This cannot be undone.`))return;try{await request(`/contacts/${id}`,{method:'DELETE'});if(selectedContact?.id===id){selectedContact=null;$('#contactEmpty').hidden=false;$('#contactInsight').hidden=true}await refreshData();notify('Contact permanently deleted')}catch(error){notify(error.message)}}$('#newContactBtn').onclick=openContactModal;$('#newContactLive').onclick=openContactModal;$('#contactClose').onclick=()=>contactModal.classList.remove('open');
async function scanCard(file){const form=new FormData();form.append('image',file,file.name||'business-card.jpg');notify('Reading the real card with Qwen-VL...');try{const data=await upload('/ai/business-card',form),result=data.result||{};openContactModal();$('#contactName').value=result.name||'';$('#contactCompany').value=result.company||'';$('#contactRole').value=result.role||'';$('#contactInterests').value=Array.isArray(result.interests)?result.interests.join(', '):'';notify('Card fields extracted - verify before saving')}catch(error){notify(error.message)}}
$('#cardBtn').onclick=async()=>{if(stream&&$('#cameraVideo').videoWidth){const video=$('#cameraVideo'),canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(blob=>scanCard(new File([blob],'business-card.jpg',{type:'image/jpeg'})),'image/jpeg',.9)}else $('#cardFile').click()};$('#cardFile').onchange=e=>{if(e.target.files[0])scanCard(e.target.files[0]);e.target.value=''};
$('#contactForm').onsubmit=async e=>{e.preventDefault();try{const body={name:$('#contactName').value.trim(),company:$('#contactCompany').value.trim(),role:$('#contactRole').value.trim(),interests:$('#contactInterests').value.split(',').map(x=>x.trim()).filter(Boolean),score:Number($('#contactScore').value)},saved=await request(editingContactId?`/contacts/${editingContactId}`:'/contacts',{method:editingContactId?'PATCH':'POST',body:JSON.stringify(body)});contactModal.classList.remove('open');await refreshData();selectContact(saved.id);notify(editingContactId?'Contact updated':'Real contact saved')}catch(error){notify(error.message)}};
$('#exportBtn').onclick=()=>{if(!contacts.length)return notify('No contacts to export');const csv=['Name,Company,Role,Interests,Score',...contacts.map(x=>`"${x.name}","${x.company}","${x.role}","${x.interests}",${x.score}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='expomind-contacts.csv';a.click();URL.revokeObjectURL(a.href)};

function renderTasks(){const items=conversations.filter(x=>x.next_action?.trim());$('#taskBoard').innerHTML=items.length?`<section class="task-column"><div class="task-column-head"><b>Saved actions</b><span>${items.length}</span></div>${items.map(x=>`<article class="task-card"><span class="priority">${escapeHtml(x.contact_name)}</span><h3>${escapeHtml(x.next_action)}</h3><p>${escapeHtml(x.summary||'No summary recorded')}</p><div class="task-meta"><span>${new Date(x.created_at).toLocaleString()} · ${escapeHtml(x.company)}</span></div></article>`).join('')}</section>`:'<div class="list-empty">No follow-up actions have been recorded.</div>'}
function renderGraph(){const svg=$('#graphSvg');if(!contacts.length){svg.innerHTML='<text x="450" y="280" text-anchor="middle" fill="#748497">Create contacts to build the real relationship graph</text>';return}const cx=450,cy=280,radius=190,nodes=contacts.map((x,i)=>({id:x.id,x:cx+Math.cos(i*2*Math.PI/contacts.length)*radius,y:cy+Math.sin(i*2*Math.PI/contacts.length)*radius,label:x.name}));svg.innerHTML=nodes.map(n=>`<line class="graph-line" x1="${cx}" y1="${cy}" x2="${n.x}" y2="${n.y}"/>`).join('')+`<g class="graph-node" transform="translate(${cx} ${cy})" style="color:#5a96f8"><circle r="38" fill="#5a96f822" stroke="#5a96f8"/><text y="58">${escapeHtml(currentUser.name)}</text></g>`+nodes.map(n=>`<g class="graph-node" data-id="${n.id}" transform="translate(${n.x} ${n.y})" style="color:#55dfce"><circle r="27" fill="#55dfce22" stroke="#55dfce"/><text y="45">${escapeHtml(n.label)}</text></g>`).join('');$$('.graph-node[data-id]',svg).forEach(g=>g.onclick=()=>selectContact(Number(g.dataset.id)))}

async function loadUsers(){if(currentUser?.role!=='admin')return;try{const [users,logs]=await Promise.all([request('/admin/users'),request('/admin/audit-logs')]);$('#userList').innerHTML=users.map(u=>`<div class="user-admin-row"><div><b>${escapeHtml(u.name)}</b><small>${escapeHtml(u.email)}</small></div><small>${new Date(u.created_at).toLocaleString()}</small><span>${u.contact_count} contacts</span><select data-role="${u.id}"><option value="user" ${u.role==='user'?'selected':''}>User</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select><button data-toggle="${u.id}" data-active="${u.is_active}">${u.is_active?'Disable':'Enable'}</button></div>`).join('');$('#auditList').innerHTML=logs.length?logs.map(x=>`<div class="audit-row"><b>${escapeHtml(x.actor)}</b><span>${escapeHtml(x.action)}</span><span>${escapeHtml(x.target_type)} #${x.target_id??'-'}</span><span>${new Date(x.created_at).toLocaleString()} · ${escapeHtml(x.detail)}</span></div>`).join(''):'<div class="list-empty">No administrator changes recorded.</div>';$$('[data-role]').forEach(s=>s.onchange=()=>updateUser(Number(s.dataset.role),{role:s.value}));$$('[data-toggle]').forEach(b=>b.onclick=()=>updateUser(Number(b.dataset.toggle),{is_active:b.dataset.active!=='true'}))}catch(error){notify(error.message)}}
async function updateUser(id,body){try{await request(`/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(body)});await loadUsers();notify('User updated')}catch(error){notify(error.message)}}$('#refreshUsers').onclick=loadUsers;

let detector=null;async function createDetector(){if('FaceDetector'in window){const nativeDetector=new FaceDetector({fastMode:true,maxDetectedFaces:4});return{detect:video=>nativeDetector.detect(video)}}const vision=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');const files=await vision.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');const mp=await vision.FaceDetector.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite'},runningMode:'VIDEO',minDetectionConfidence:.55});return{detect:async video=>{const result=mp.detectForVideo(video,performance.now());return result.detections.map(d=>({boundingBox:{x:d.boundingBox.originX,y:d.boundingBox.originY,width:d.boundingBox.width,height:d.boundingBox.height}}))}}}
function moveFaceBox(box){const video=$('#cameraVideo'),feed=$('#cameraFeed'),face=$('.face-box'),scan=$('.scan-line'),scale=Math.max(feed.clientWidth/video.videoWidth,feed.clientHeight/video.videoHeight),offsetX=(feed.clientWidth-video.videoWidth*scale)/2,offsetY=(feed.clientHeight-video.videoHeight*scale)/2;const left=box.x*scale+offsetX,top=box.y*scale+offsetY,width=box.width*scale,height=box.height*scale;for(const el of [face,scan]){el.classList.remove('no-face');el.style.left=`${left}px`;el.style.top=`${top}px`;el.style.width=`${width}px`}face.style.height=`${height}px`;$('.match').textContent='Face detected · identity unknown'}
async function trackingLoop(){if(!tracking||!stream)return;try{const faces=await detector.detect($('#cameraVideo'));if(faces.length){const box=faces.sort((a,b)=>(b.boundingBox.width*b.boundingBox.height)-(a.boundingBox.width*a.boundingBox.height))[0].boundingBox;moveFaceBox(box)}else{$('.face-box').classList.add('no-face');$('.scan-line').classList.add('no-face')}}catch(e){}requestAnimationFrame(trackingLoop)}
const consentModal=$('#consentModal');$('#cameraBtn').onclick=()=>consentModal.classList.add('open');$('#modalClose').onclick=()=>consentModal.classList.remove('open');$('#consentCheck').onchange=e=>$('#consentContinue').disabled=!e.target.checked;
$('#consentContinue').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280},height:{ideal:720}},audio:false});const video=$('#cameraVideo');video.srcObject=stream;await video.play();$('#cameraFeed').classList.add('camera-on');$('#liveState').textContent='LIVE';consentModal.classList.remove('open');const started=Date.now();setInterval(()=>{if(!stream)return;const elapsed=Math.floor((Date.now()-started)/1000),h=String(Math.floor(elapsed/3600)).padStart(2,'0'),m=String(Math.floor(elapsed%3600/60)).padStart(2,'0'),s=String(elapsed%60).padStart(2,'0');$('#liveTimer').textContent=`${h}:${m}:${s}`},1000);detector=await createDetector();tracking=true;trackingLoop();notify('Live face tracking started')}catch(error){notify(`Camera or face detector unavailable: ${error.message}`)}};
$('#captureBtn').onclick=()=>notify(selectedContact?'Frame captured for the selected contact':'Face detected only. Select a verified contact to attach data.');
$('#recordBtn').onclick=()=>{const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API)return notify('Speech recognition is unavailable in this browser');if(!recognition){recognition=new API();recognition.continuous=true;recognition.interimResults=true;recognition.lang='zh-CN';recognition.onresult=e=>{const text=[...e.results].map(x=>x[0].transcript).join('');$('#transcript').textContent=text;$('#liveTranscriptCopy').textContent=text};recognition.onend=()=>{$('#listenState').textContent='Conversation paused';$('#recordBtn small').textContent='Start voice'}}recognition.start();$('#listenState').textContent='Listening and transcribing real audio...';$('#recordBtn small').textContent='Listening'};
$('#analyzeBtn').onclick=async()=>{const transcript=$('#transcript').textContent.trim();if(!transcript||transcript==='No transcript recorded.')return notify('Record a real transcript first');const button=$('#analyzeBtn');button.disabled=true;button.textContent='Analyzing...';try{const data=await request('/ai/analyze-transcript',{method:'POST',body:JSON.stringify({transcript})});lastAnalysis=data.result;$('#analysisSummary').textContent=lastAnalysis.summary||'No supported summary returned.';$('#analysisEvidence').innerHTML=(lastAnalysis.evidence||[]).map(x=>`<span>${escapeHtml(x)}</span>`).join('');$('#nextAction').value=lastAnalysis.next_action||'';if(selectedContact&&Number.isInteger(lastAnalysis.score)){$('#score').textContent=`${lastAnalysis.score}%`;$('#scoreBar').style.width=`${lastAnalysis.score}%`}notify('Qwen analysis completed from the real transcript')}catch(error){notify(error.message)}finally{button.disabled=false;button.textContent='Analyze real transcript'}};
$('#saveBtn').onclick=async()=>{if(!selectedContact)return notify('Select a real contact first');const transcript=$('#transcript').textContent.trim(),nextAction=$('#nextAction').value.trim();if(!transcript||transcript==='No transcript recorded.')return notify('Record a real transcript before saving');try{await request('/conversations',{method:'POST',body:JSON.stringify({contact_id:selectedContact.id,transcript,summary:lastAnalysis?.summary||'',next_action:nextAction,score:lastAnalysis?.score||selectedContact.score})});if(lastAnalysis){await request(`/contacts/${selectedContact.id}`,{method:'PATCH',body:JSON.stringify({interests:lastAnalysis.interests||selectedContact.interests.split(',').filter(Boolean),score:lastAnalysis.score??selectedContact.score})})}lastAnalysis=null;await refreshData();notify('Real conversation saved to PostgreSQL')}catch(error){notify(error.message)}};
$('#privacyBtn').onclick=e=>{const on=e.currentTarget.classList.toggle('on');e.currentTarget.textContent=on?'Privacy mode: ON':'Privacy mode';notify(on?'Raw media stays on this device':'Standard processing restored')};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')$('#saveBtn').click()});window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));if(token)request('/auth/me').then(showWorkspace).catch(()=>logout(false));else setAuthMode('login');
